### ISSUE TITLE
Vencord gets unlogged every time i close the app.

### ISSUE THREAD

**Issue by enderpuff** [Vencord/Desktop#34]
Self explaining

**Comment by Vendicated** [comment]
unlogged?

**Comment by enderpuff** [comment]
My account gets logged out. That's on 0.2.0, linux client

**Comment by Vendicated** [comment]
which package type did you use?

**Comment by Vendicated** [comment]
that's strange, i haven't changed anything between those versions that would cause it

**Comment by enderpuff** [comment]
I will close this as it seems to have stopped. I will re-open it if the issue starts appearing again

**Comment by Devetec** [comment]
this keeps happening to me now...

**Comment by Vendicated** [comment]
Apparently this is caused by you closing Discord via CTRL+C. Or there is an issue with Electron's data persistence. Observe the console for errors and try reinstalling

**Comment by enderpuff** [comment]
The issue seems to be happening again on 0.2.6 for me. It only unlogs my main account, though, my secondary stays logged for some reason

**Comment by Devetec** [comment]
> Apparently this is caused by you closing Discord via CTRL+C. Or there is an issue with Electron's data persistence. Observe the console for errors and try reinstalling
> 
> Closing as wontfix because this is not under our control

@Vendicated It isn't due to closing Discord with CTRL+C.
I was able to reproduce this by adding another Discord account to Vencord and then closing it with the "x" in the top-right corner. When reopening the app, the first Discord account will have been logged-out of, and it will prompt you to choose to log into the second Discord account.
